"""Author pixel sprites as text grids, validate them, and emit client/src/render/sprite-data.ts."""
import sys, json

# Palette (shared by every sprite). 'b'/'B' are the class colour (light/dark), filled in at render time.
PALETTE = {
    'k': '#140f0b',  # outline
    's': '#e8c49a', 'S': '#b08458',  # skin
    'w': '#d4d8e2', 'W': '#8a92a6',  # steel
    'y': '#f2d266', 'Y': '#b08a30',  # gold / lamp
    't': '#ffb030', 'T': '#ff6a20',  # flame
    'r': '#c63a32', 'R': '#6e1c18',  # red / blood
    'g': '#8aa070', 'G': '#4e6440',  # ghoul flesh
    'c': '#e2dac6', 'C': '#9e957e',  # bone
    'p': '#a07ad6', 'P': '#5c3c8c',  # violet
    'd': '#3c3128', 'D': '#241c16',  # dark cloth
    'n': '#7a5a3c', 'N': '#4c3624',  # brown
    'e': '#ff4a30',  # glowing eyes
    'o': '#ffffff',
    'v': '#9a7a5a', 'V': '#6a5038',  # villager cloth
    'x': '#2a2a30',  # chain / iron
}

SPRITES = {
'warden': """
................
.....kkkkkk.....
....kwwwwwwk....
....kwkkkkwk....
....kwwwwwwk....
.....kWWWWk.....
..kkkkbbbbkkk...
.kwwwkbbbbbbbk..
kwWWWwkbBBbbsk..
kwWyWwkbbbbbsk..
kwWWWwkbbbbbk...
.kwwwkbBbbBbk...
..kkk.kbbkbbk...
......kBk.kBk...
......kWk.kWk...
......kkk.kkk...
""",
'cutthroat': """
................
......kkkk......
.....kBBBBk.....
....kBbbbbBk....
....kBkeekBk....
....kBdssdBk....
.....kBbbBk.....
...kkbbbbbbkk...
..kskbbBBbbksk..
..kskbbbbbbkwk..
...kkbbbbbbkwk..
....kbBbbBbkWk..
....kbbkkbbkk...
....kDDk.kDDk...
....kDDk.kDDk...
....kkk...kkk...
""",
'lampbearer': """
................
.....kkkkkk.....
....kbbbbbbk....
....kbkkkkbk....
....kkssssk.....
.....kssssk.....
..k..kkbbkk.....
.kyk.kbbbbbk....
kyttykbbbbbbk...
kytTykbBbbBbsk..
kyttyk.kbbbbsk..
.kyk..kbbbbbk...
..k..kbbbbbbk...
....kbbbbbbbbk..
....kBBBBBBBBk..
....kkkkkkkkkk..
""",
'sorceress': """
.......kk.......
......kbbk......
.....kbbbbk.....
....kbbbbbbk....
....kbkeekbk....
....kbdddDbk....
...kbbbddbbbk...
..kbbbbbbbbbbk..
.kpkbbbBBbbbkpk.
.kpkbbbbbbbbkpk.
..k.kbbbbbbk.k..
....kbbbbbbk....
....kbBbbBbk....
...kbbbbbbbbk...
...kBBBBBBBBk...
...kkkkkkkkkk...
""",
'undertaker': """
.....kkkkk......
.....kDDDk......
.....kDDDk......
....kkkkkkk.....
.....kssk....k..
.....kSSk...kNk.
....kkbbkk..kNk.
...kbbbbbbk.kNk.
..kbbBbbBbbksNk.
..kbbbbbbbbkkNk.
..kbbBbbBbbk.kNk
...kbbbbbbk.kWWk
...kbbbbbbk.kWWk
...kBBkkBBk..kk.
...kDDk.kDDk....
...kkkk.kkkk....
""",
'bellwright': """
................
.....kkkkk......
....kbbbbbk.....
....kbkkkbk.....
....kkssskk.....
.....ksssk......
...kkbbbbbkk....
..kbbbbbbbbbk...
.kbbBbbbbBbbsk..
.kbbbbbbbbbkNk..
..kbbBbbbBbkYk..
..kbbbbbbbkyyyk.
..kbbbbbbbkyYyk.
..kBBBBBBBkyyyk.
..kkkkkkkkkkYkk.
...........k....
""",
'zealot': """
......kkk.......
.....kbbbk......
....kbbbbbk.....
....kbkeekk.....
....kbkssk......
....kbbkkbk.....
...kbbbbbbbk.k..
..kbbbbbbbbbkxk.
..kbbBbbBbbkskx.
..kbbbbbbbbk.kxk
...kbbBbBbk..kRk
...kbbbbbbk...k.
...kbbbbbbk.....
..kbbbbbbbbk....
..kBBBBBBBBk....
..kkkkkkkkkk....
""",
'alchemist': """
................
.....kkkkk......
....kNNNNNk.....
...kkkkkkkkk....
....kssssk......
....kwkkwk......
....kssssk......
...kkbbbbkk.....
..kbbbbbbbbk.k..
..kbbBbbBbkskwk.
..kbbbbbbbk.kgk.
..kbbBbbBbk.kggk
..kbbbbbbbk.kGgk
..kbbbbbbbk..kk.
..kBBkkkBBk.....
..kkkk.kkkk.....
""",
'ghoul': """
................
................
.....kkkk.......
....kggggk......
...kgkeegk......
...kggggGk......
....kkcckk......
..kkggggggkk....
.kgGkggggkGgk...
.kgk.kggggk.kgk.
kck..kgGGgk..kck
.k...kggggk...k.
.....kgkkgk.....
....kgk..kgk....
....kGk..kGk....
....kkk..kkk....
""",
'crawler': """
................
................
................
................
.........kkkk...
..k.k...krrrrk..
.krkrk.krRrRrrk.
..k.krkrrrrrrrek
.....krrRrrRrrek
..k.krkrrrrrrrk.
.krkrk.kRrrRrk..
..k.k...kkkkk...
....k.k.k.k.....
...k.k.k.k.k....
................
................
""",
'acolyte': """
................
......kkkk......
.....kddddk.....
....kdddddDk....
....kdkeekdk....
....kdDddDdk....
.....kkddkk.....
...kkdddddDkk...
..kdkdrrrrdkdk..
..kskdrRRrdksk..
...k.drrrrd.k...
....kdddddDk....
....kdddddDk....
...kddddddDDk...
...kDDDDDDDDk...
...kkkkkkkkkk...
""",
'giant': """
....kkkkkkkk....
...kccccccccck..
...kckeckeccck..
...kcccccccCck..
....kcCkkCcck...
..kkkkccccckkkk.
.kccckcCCcckccck
kcCCckcccccckCCk
kccckcCcCcCckcck
.kkk.kccccck.kk.
.....kcCcCck....
....kcck.kcck...
....kcck.kcck...
...kcCck.kcCck..
...kkkk...kkkk..
................
""",
'wight': """
................
.....kkkkk......
....kWWWWWk.....
...kWkeekWWk....
...kWWWWWWWk....
....kWkkkWk..kk.
...kWWWWWWWk.kyk
..kWWWWWWWWWkktk
..kWkWWWWWkWkkkk
..kk.kWWWWWk....
.....kWWWWWk....
.....kWWWWWWk...
....kWWWWWWWk...
....kWkWkWkWk...
.....k.k.k.k....
................
""",
'queen': """
......y.y.y.....
.....kyyyyyk....
.....kcccccck...
.....kceccek....
.....kccCcck....
......kcck......
....kkpppPkk....
...kpppyypppk...
..kcpppppppPck..
..kckpppppPkck..
....kpppppPk....
....kppPppPk....
...kpppPpppPk...
..kppppPppppPk..
..kPPPPPPPPPPk..
..kkkkkkkkkkkk..
""",
'zombie': """
................
.....kkkkk......
....kGgggGk.....
....kgekgek.....
....kggggGk.....
.....kgkkgk.....
...kkkknnkkkkk..
..kgGknNnnkgggk.
..kk.knnnNkkkkk.
.....knNnnk.....
.....kNnnNk.....
.....kddDdk.....
.....kdkkdk.....
....kdk..kGk....
....kGk..kgGk...
....kkk..kkkk...
""",
'lich': """
...y.y.y......k.
...kyyyk.....kek
..kcccccck....k.
..kceCcCek....kn
..kcccCcck....kn
...kckckck....kn
..kkPPPPPkk...kn
.kPpppppppPk.kkn
kPpppPppppPkkcck
kPkppPpppkPk.kn.
.k.kpPpppPk..kn.
...kpPppppPk.kn.
..kppPpppppPkkn.
..kpPPppPpppPkn.
.kPPPPPPPPPPPkn.
.kkkkkkkkkkkkkk.
""",
'villager': """
................
................
......kkkk......
.....kNNNNk.....
.....kssssk.....
.....kskksk.....
.....kssssk.....
......kkkk......
....kkvvvvkk....
...ksvvvvvvsk...
...kskvVVvksk...
....k.vvvv.k....
.....kvvvvk.....
.....kVkkVk.....
.....kNk.kNk....
.....kkk.kkk....
""",
}


def check(name, art):
    rows = [r for r in art.strip('\n').split('\n')]
    if len(rows) != 16:
        raise SystemExit(f'{name}: {len(rows)} rows')
    for i, r in enumerate(rows):
        if len(r) != 16:
            raise SystemExit(f'{name} row {i}: {len(r)} chars: {r!r}')
        for ch in r:
            if ch != '.' and ch not in PALETTE and ch not in 'bB':
                raise SystemExit(f'{name} row {i}: unknown colour {ch!r}')
    return rows


out = {n: check(n, a) for n, a in SPRITES.items()}
ts = ['// Generated by tools/sprites.py (python tools/sprites.py client/src/render/sprite-data.ts) — 16×16 pixel sprites as palette strings.',
      "// '.' = transparent, 'b'/'B' = the class colour (light/dark), other letters index PALETTE.",
      f'export const PALETTE: Record<string, string> = {json.dumps(PALETTE, indent=2)};', '',
      'export const SPRITES: Record<string, string[]> = {']
for n, rows in out.items():
    ts.append(f'  {n}: [')
    ts.extend(f"    '{r}'," for r in rows)
    ts.append('  ],')
ts.append('};')
open(sys.argv[1], 'w', encoding='utf8').write('\n'.join(ts) + '\n')
print('ok', len(out), 'sprites')
